version: '3.7'
services:
  redis:
    image: redis:latest
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"
  db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c "python -m bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis


volumes:
  pgdata: